spring.application.name=nbody

mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=server
mqtt.qos = 1

mqtt.topic.outgoing.simulation=simulation

mqtt.topic.incoming.simulation-event-add=simulation/event/add
mqtt.topic.incoming.simulation-event-move=simulation/event/move
mqtt.topic.incoming.simulation-event-delete=simulation/event/delete
mqtt.topic.incoming.simulation-event-pause=simulation/event/pause
mqtt.topic.incoming.simulation-preset=simulation/preset